# Generated by Django 5.2.4 on 2025-07-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passcode',
            fields=[
                ('code', models.TextField(help_text='Ключ', primary_key=True, serialize=False)),
            ],
        ),
    ]
