# Generated by Django 4.2.23 on 2025-09-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pow', '0002_security_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powchallenge',
            name='difficulty',
            field=models.IntegerField(default=5),
        ),
    ]
