# Generated by Django 5.2.4 on 2025-07-25 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anon',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('banned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('code', models.CharField(help_text='Код доски (например, b)', max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Описание доски, которое видят пользователи в её шапке')),
                ('banner', models.FileField(help_text='Приветственный баннер', null=True, upload_to='')),
                ('thread_limit', models.IntegerField(default=1000, help_text='Количество тредов, при котором старые начнут удаляться, давая место новым (0 для неограниченного количества)')),
            ],
            options={
                'permissions': [('upload_large_files', 'Can upload large files')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now=True, help_text='Дата и время создания')),
                ('anon', models.BooleanField(default=False, help_text='Скрыть имя от отсальных участников (админы всё ещё могут увидеть ник)')),
                ('text', models.TextField(help_text='Текст')),
                ('author', models.ForeignKey(help_text='Создатель треда', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файл', null=True, upload_to='')),
                ('comment', models.ForeignKey(help_text='Коммент, которому принадлежит файл', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now=True, help_text='Дата и время создания')),
                ('anon', models.BooleanField(default=False, help_text='Скрыть имя от отсальных участников (админы всё ещё могут увидеть ник)')),
                ('title', models.CharField(default='None', help_text='Заголовок', max_length=64)),
                ('text', models.TextField(help_text='Текст')),
                ('author', models.ForeignKey(help_text='Создатель треда', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(help_text='Доска треда', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.board')),
            ],
            options={
                'permissions': [('create_new_threads', 'Can create new threads'), ('comment_threads', 'Can comment threads')],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(help_text='Тред, к которому пишется комментарий', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.thread'),
        ),
        migrations.CreateModel(
            name='ThreadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файл', null=True, upload_to='')),
                ('thread', models.ForeignKey(help_text='Тред, которому принадлежит файл', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.thread')),
            ],
        ),
    ]
