# Generated by Django 5.2.4 on 2025-07-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='thread_limit',
            field=models.IntegerField(default=1000, help_text='Количество тредов, при котором старые начнут удаляться, давая место новым (не указывайте для неограниченного количества)', null=True),
        ),
    ]
