# Generated by Django 4.2.23 on 2025-09-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='Создатель треда', null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.anon'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(help_text='Тред, к которому пишется комментарий', null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.thread'),
        ),
        migrations.AlterField(
            model_name='commentfile',
            name='comment',
            field=models.ForeignKey(help_text='Коммент, которому принадлежит файл', null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.comment'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='author',
            field=models.ForeignKey(help_text='Создатель треда', null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.anon'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='board',
            field=models.ForeignKey(help_text='Доска треда', null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.board'),
        ),
        migrations.AlterField(
            model_name='threadfile',
            name='thread',
            field=models.ForeignKey(help_text='Тред, которому принадлежит файл', null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.thread'),
        ),
    ]
