# Generated by Django 5.2.4 on 2025-08-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='detail_description',
            field=models.TextField(help_text='Подробное описание доски, видно которое пользователи видят в шапке самой доски', null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(help_text='Короткое описание доски, которое пользователи видят в списке рядом с ней'),
        ),
    ]
