# Generated by Django 5.2.4 on 2025-07-25 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='Создатель треда', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.anon'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='author',
            field=models.ForeignKey(help_text='Создатель треда', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.anon'),
        ),
    ]
