# Generated by Django 4.2.23 on 2025-09-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anon',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='board',
            name='permissions_required',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
