# Generated by Django 4.2.23 on 2025-11-10 18:34

import boards.tools
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_board_category_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanReason',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Причина бана по этому коду. Желательно чтоб была понятной.')),
            ],
        ),
        migrations.AlterField(
            model_name='commentfile',
            name='file',
            field=models.FileField(help_text='Файл', null=True, upload_to=boards.tools.anonymous_file_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'mp4', 'webm', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='threadfile',
            name='file',
            field=models.FileField(help_text='Файл', null=True, upload_to=boards.tools.anonymous_file_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'mp4', 'webm', 'gif'])]),
        ),
        migrations.CreateModel(
            name='BanCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Подробное описание конкретного случая бана. Можно не писать, тогда будет показано описание причины бана.')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.banreason')),
            ],
        ),
        migrations.AlterField(
            model_name='anon',
            name='banned',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='boards.bancase'),
        ),
    ]
