# Generated by Django 5.2.4 on 2025-08-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_detail_description_alter_board_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_code',
            field=models.TextField(default=None, help_text='Код автора, задаётся автоматически.'),
            preserve_default=False,
        ),
    ]
