# Generated by Django 4.2.23 on 2025-11-06 08:34

import boards.tools
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_board_category_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentfile',
            name='file',
            field=models.FileField(help_text='Файл', null=True, upload_to=boards.tools.anonymous_file_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'mp4', 'webm', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='threadfile',
            name='file',
            field=models.FileField(help_text='Файл', null=True, upload_to=boards.tools.anonymous_file_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'mp4', 'webm', 'gif'])]),
        ),
    ]
