# Generated by Django 4.2.23 on 2025-09-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_anon_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anon',
            name='id',
        ),
        migrations.AlterField(
            model_name='anon',
            name='ip',
            field=models.GenericIPAddressField(primary_key=True, serialize=False, unique=True),
        ),
    ]
