# Generated by Django 5.2.4 on 2025-07-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_comment_author_alter_thread_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='anon',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='anon',
        ),
    ]
