# Generated by Django 5.2.4 on 2025-08-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_commentfile_file_alter_threadfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bump_limit',
            field=models.IntegerField(default=500, help_text="Бамплимит. При достижении (бамплимит) комментариев в треде он 'утонет' (удалится) (0 для выключения бамплимита)"),
        ),
        migrations.AlterField(
            model_name='board',
            name='banner',
            field=models.FileField(default=None, help_text='Приветственный баннер', null=True, upload_to=''),
        ),
    ]
