# Generated by Django 5.2.4 on 2025-07-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_thread_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='banner',
            field=models.FileField(help_text='Приветственный баннер', null=True, upload_to=''),
        ),
    ]
