# Generated by Django 5.2.4 on 2025-07-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_comment_anon_remove_thread_anon'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='archived',
            field=models.BooleanField(default=False, help_text='Заархивирован ли тред? Заархивированные треды нельзя комментировать и они отображаются на отдельной странице.'),
        ),
    ]
