# Generated by Django 4.2.23 on 2025-11-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_banreason_alter_commentfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancase',
            name='ban_pic',
            field=models.ImageField(blank=True, default=None, help_text='Сделано ради прикола. Если задана, будет высвечивтаься на странице бана.', null=True, upload_to=''),
        ),
    ]
