# Generated by Django 5.2.4 on 2025-08-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_comment_author_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_code',
            field=models.TextField(default=None, help_text='Код автора, задаётся автоматически.', null=True),
        ),
    ]
