# Generated by Django 5.2.4 on 2025-08-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_board_bump_limit_alter_board_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='enable_posting',
            field=models.BooleanField(default=True, help_text='Если False, разрешает постинг в борде только админам (борда всё ещё будет доступна для просмотра из списка)'),
        ),
    ]
