# Generated by Django 4.2.23 on 2025-11-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_bancase_ban_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='archived',
            field=models.BooleanField(default=False, help_text='Архивация треда'),
        ),
    ]
