# Generated by Django 5.2.4 on 2025-07-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_thread_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon',
            name='code',
            field=models.TextField(default='anon'),
        ),
    ]
