# Generated by Django 5.2.4 on 2025-08-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_comment_author_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_nsfw',
            field=models.BooleanField(default=False, help_text='Помечает борд как NSFW. Файлы с тредов в NSFW бордах отправляются МКБотом под спойлером, а сама категория помечается красным цветом.'),
        ),
    ]
