# Generated by Django 5.2.4 on 2025-07-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_thread_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='banner',
        ),
        migrations.AddField(
            model_name='board',
            name='banner',
            field=models.FileField(help_text='Приветственный баннер', null=True, upload_to=''),
        ),
    ]
