# Generated by Django 5.2.4 on 2025-07-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_remove_thread_banner_board_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(default='None', help_text='Заголовок', max_length=64),
        ),
    ]
