# Generated by Django 5.2.4 on 2025-08-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_category_board_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anon',
            name='code',
        ),
        migrations.AddField(
            model_name='thread',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Если тред закреплён, он будет отображаться в самом начале списка тредов. Также можно задать из контектного меню треда если вы админ.'),
        ),
    ]
