# Generated by Django 5.2.4 on 2025-08-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_board_is_nsfw'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_nsfw',
            field=models.BooleanField(default=False, help_text='Является ли коммент NSFW (всегда True для комментов под NSFW тредами)'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_nsfw',
            field=models.BooleanField(default=False, help_text='Является ли тред NSFW (всегда True для комментов на NSFW бордах)'),
        ),
    ]
