# Generated by Django 4.2.23 on 2025-11-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_commentfile_file_alter_threadfile_file'),
        ('boards', '0005_thread_archived'),
    ]

    operations = [
    ]
