# Generated by Django 5.2.4 on 2025-07-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_anon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='archived',
        ),
    ]
