# Generated by Django 4.2.23 on 2025-11-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_merge_20251119_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bump_limit',
            field=models.IntegerField(default=500, help_text="Бамплимит. При достижении (бамплимит) комментариев в треде он 'утонет' (перейдёт в read-only архив) (0 для выключения бамплимита)"),
        ),
    ]