# Generated by Django 5.2.4 on 2025-08-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_remove_anon_code_thread_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='rating',
            field=models.IntegerField(default=0, help_text='Рейтинг треда. Он задаётся автоматически, крайне не рекомендуется менять вручную!!!'),
        ),
    ]
