# Generated by Django 5.2.4 on 2025-08-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_thread_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='lockdown',
            field=models.BooleanField(default=False, help_text='Карантин. В карантинных бордах НЕЛЬЗЯ создавать или бампать треды.'),
        ),
    ]
