# Generated by Django 4.2.23 on 2025-11-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_board_bump_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='persistent',
            field=models.BooleanField(default=False, help_text='Тред с этим полем, выставленным в true, никогда не утонет и будет висеть в списке.'),
        ),
    ]
